#!/usr/bin/env node
/**
 * Expand / refresh Orbital celebration joke library.
 * Inspired by classic programmer humor (e.g. shrutikapoor08/devjoke themes).
 * Run: node scripts/expand-bites.mjs
 *
 * Agents: append more entries to SOURCES below, then re-run.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const OUT = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
  'media',
  'content',
  'bites.json',
);

const ANIMS = [
  'glitch-text',
  'typewriter',
  'bounce-in',
  'stamp-spin',
  'slide-up',
  'confetti',
  'pulse-zoom',
  'float-soft',
];

/** [line, subline, tone] — kinds=* packs=* unless noted */
const SOURCES = [
  // Classic-style programmer jokes (original Orbital phrasing)
  ['THERE ARE ONLY 10 TYPES OF PEOPLE', 'those who get binary jokes · and those who don’t', 'joke'],
  ['A SQL QUERY WALKS INTO A BAR', 'sees two tables · “can I JOIN you?”', 'joke'],
  ['!FALSE', 'it’s funny because it’s true', 'joke'],
  ['SEMICOLONS · THE SILENT KILLERS', 'until they’re missing', 'joke'],
  ['IT WORKS ON MY MACHINE', 'ship the machine', 'satire'],
  ['99 LITTLE BUGS IN THE CODE', 'take one down · 127 bugs in the code', 'joke'],
  ['RECURSIVE FUNCTION TO EXPLAIN RECURSION', 'see: recursive function to explain recursion', 'joke'],
  ['HARDWARE: THE PART YOU KICK', 'software: the part you yell at', 'joke'],
  ['I WOULD TELL YOU A UDP JOKE', 'you might not get it', 'joke'],
  ['TCP JOKE RECEIVED', 'ACK · thanks for laughing', 'joke'],
  ['GIT COMMIT -M “FIX”', 'future archaeologists will hate you', 'satire'],
  ['GIT PUSH --FORCE', 'with great power comes great outage', 'satire'],
  ['MERGE CONFLICT IN THE HEART', 'accept theirs · regret yours', 'joke'],
  ['STACK OVERFLOW COPY · PASTE · PRAY', 'ancient ritual · still works', 'satire'],
  ['DOCUMENTATION IS LIKE SEX', 'when it’s good it’s very good · when it’s bad…', 'joke'],
  ['CSS IS AWESOME', 'the box is bigger than the overflow', 'joke'],
  ['HORIZONTAL CENTERING SOLVED', 'for now · until mobile', 'satire'],
  ['ASYNC AWAIT MY COFFEE', 'promise pending…', 'joke'],
  ['NULL POINTER EXCEPTION', 'object’s feelings: undefined', 'joke'],
  ['UNDEFINED IS NOT A FUNCTION', 'but neither am I before coffee', 'joke'],
  ['404: JOKE NOT FOUND', 'try /humor again', 'joke'],
  ['500: INTERNAL SERVER SASS', 'the backend is judging you', 'satire'],
  ['CORS SAID NO', 'the browser is a helicopter parent', 'joke'],
  ['NPM INSTALL THE PROBLEMS', 'node_modules: larger than your hopes', 'satire'],
  ['LEFT PAD INCIDENT PTSD', 'never forget · always pin', 'satire'],
  ['YARN WHY NOT', 'package managers: collect them all', 'joke'],
  ['DOCKER: IT WORKS IN THE CONTAINER', 'production is not a container · yet', 'satire'],
  ['KUBERNETES: YAML HELL', 'indent or die', 'satire'],
  ['MICROSERVICES: NOW YOU HAVE 12 PROBLEMS', 'distributed chaos as a service', 'satire'],
  ['MONOLITH SAID HOLD MY BEER', 'and still shipped faster', 'joke'],
  ['AGILE: WE MOVE FAST', 'and break the sprint board', 'satire'],
  ['STORY POINTS: FIBONACCI OF LIES', 'estimate: 5 · reality: ∞', 'satire'],
  ['STANDUP COULD’VE BEEN AN EMAIL', 'and the email could’ve been silence', 'satire'],
  ['JIRA TICKET IN PROGRESS', 'since the Mesozoic', 'joke'],
  ['CODE REVIEW: LGTM', 'looks good to merge · I skimmed', 'satire'],
  ['NIT: RENAME VARIABLE', 'the eternal bikeshed', 'joke'],
  ['APPROVED WITH COMMENTS', 'none of which you’ll address', 'satire'],
  ['HOTFIX ON FRIDAY', 'bold · cursed · iconic', 'satire'],
  ['DEPLOY ON FRIDAY', 'see you Monday · maybe', 'joke'],
  ['ROLLBACK IS A FEATURE', 'shipped confidence · returned humility', 'joke'],
  ['FEATURE FLAG: OFF', 'we were never here', 'joke'],
  ['A/B TEST YOUR SANITY', 'variant B is sleep', 'joke'],
  ['TECH DEBT INTEREST RATE: 29.9% APR', 'minimum payment: one TODO', 'satire'],
  ['TODO: FIX THIS', 'committed in 2019', 'joke'],
  ['FIXME: EVERYTHING', 'accurate ticket title', 'joke'],
  ['HACK: DON’T TOUCH', 'so of course you will', 'joke'],
  ['LEGACY CODE: FEAR THE ANCIENTS', 'comments in a dead language', 'joke'],
  ['REFACTOR = REWRITE', 'manager doesn’t need to know', 'satire'],
  ['CLEAN CODE · DIRTY DEADLINE', 'principles vs calendar', 'satire'],
  ['DRY UNTIL YOU CRY', 'then copy-paste with dignity', 'joke'],
  ['YAGNI UNTIL YOU NEEDED IT', 'yesterday', 'joke'],
  ['PREMATURE OPTIMIZATION', 'root of all evil · and all PRs', 'joke'],
  ['CACHE INVALIDATION', 'still one of the hard problems', 'joke'],
  ['OFF-BY-ONE ERRORS', 'in my jokes · and my loops', 'joke'],
  ['INFINITE LOOP OF DENIAL', 'while (bugs) { ignore(); }', 'joke'],
  ['RACE CONDITION: SOMETIMES FUNNY', 'heisenbug entered the chat', 'joke'],
  ['HEISENBUG OBSERVED', 'behavior changed · science!', 'joke'],
  ['SEGFAULT: CORE DUMPED', 'personality too', 'joke'],
  ['PERMISSION DENIED', 'sudo make me a sandwich', 'joke'],
  ['DISK FULL OF MEMES', 'not of backups', 'satire'],
  ['BACKUP FAILED SILENTLY', 'like my last relationship', 'joke'],
  ['PROD IS THE NEW STAGING', 'YOLO devops', 'satire'],
  ['STAGING LIED TO US', 'again', 'joke'],
  ['LOCALHOST: TRUSTED FRIEND', '0.0.0.0: chaos', 'joke'],
  ['PING 8.8.8.8', 'at least Google likes me', 'joke'],
  ['WIFI DOWN · PRODUCTIVITY UP', 'forced focus mode', 'wholesome'],
  ['RUBBER DUCK DEBUGGING WORKS', 'the duck union demands raises', 'joke'],
  ['PRINT STATEMENT DEBUGGING', 'old gods · still worshipped', 'joke'],
  ['BREAKPOINT NEVER HIT', 'just like my sleep schedule', 'joke'],
  ['STEPPING OVER THE BUG', 'literally', 'joke'],
  ['FLAKY TEST PASSED', 'don’t ask how', 'satire'],
  ['FLAKY TEST FAILED', 'blame the moon phase', 'joke'],
  ['COVERAGE 100% · LOGIC 12%', 'metrics are a lifestyle', 'satire'],
  ['UNIT TESTS: THE GOOD KIND OF RED', 'until green · then ship', 'hype'],
  ['E2E TEST: END TO EMOTIONAL DAMAGE', 'puppeteer of my tears', 'joke'],
  ['SNAPSHOT UPDATED', 'tests green · app wrong · ship it', 'satire'],
  ['MOCKED THE WORLD', 'and still failed assertions', 'joke'],
  ['ASSERT TRUE === TRUE', 'peak enterprise', 'satire'],
  ['TYPE ERROR: ANYWHERE', 'TypeScript tried · you used any', 'joke'],
  ['AS ANY AS YOU WANT', 'type safety optional · vibes required', 'satire'],
  ['STRICT NULL CHECKS', 'my heart: also nullable', 'joke'],
  ['OPTIONAL CHAINING SAVED ME', 'obj?.hope?.exists', 'wholesome'],
  ['SPREAD OPERATOR EVERYWHERE', '...chaos', 'joke'],
  ['DESTRUCTURED MY LIFE', 'const { sleep } = weekend', 'joke'],
  ['CLOSURE OVER MY PROBLEMS', 'still in scope', 'joke'],
  ['THIS IS UNDEFINED', 'classic JS plot twist', 'joke'],
  ['PROTOTYPE POLLUTION IN MY SOUL', 'don’t extend Object', 'joke'],
  ['EVENT LOOP: STILL SPINNING', 'macrotask: cry', 'joke'],
  ['PROMISE.RACE AGAINST DEADLINE', 'deadline always wins', 'joke'],
  ['UNHANDLED REJECTION', 'of my weekend plans', 'joke'],
  ['MEMORY LEAK OF AMBITION', 'GC won’t save you', 'joke'],
  ['OOM: OUT OF MOTIVATION', 'restart the process (you)', 'joke'],
  ['CPU AT 100% THINKING', 'about snacks', 'joke'],
  ['GPU FOR TRAINING', 'my patience', 'joke'],
  ['LLM WROTE THIS JOKE', 'human approved · barely', 'satire'],
  ['PROMPT ENGINEERING MY LIFE', 'system: be funny · user: ship', 'joke'],
  ['AGENT FIXED IT', 'human claimed credit', 'satire'],
  ['PAIR PROGRAMMING WITH COPILOT', 'third wheel: Stack Overflow', 'joke'],
  ['AI HALLUCINATED A FIX', 'tests: somehow green', 'satire'],
  ['CHATGPT SAID LGTM', 'ship behind legal’s back', 'satire'],
  ['TOKEN LIMIT REACHED', 'just like my patience', 'joke'],
  ['CONTEXT WINDOW FULL OF TRAUMA', 'summarize and continue', 'joke'],
  ['FINE-TUNED ON COFFEE', 'inference: ship', 'hype'],
  ['EMBEDDINGS OF MY REGRET', 'cosine similarity: high', 'joke'],
  ['VECTOR DB OF BAD IDEAS', 'nearest neighbor: this PR', 'joke'],
  ['RAG ON MY COMMIT MESSAGES', 'retrieved: “wip”', 'satire'],
  ['ZERO-SHOT DEPLOYMENT', 'few-shot rollback', 'joke'],
  ['MULTI-AGENT CHAOS', 'orchestration optional', 'satire'],
  ['HUMAN IN THE LOOP', 'loop: coffee → code → cry', 'joke'],
  ['EVALS PASSED', 'vibes: immaculate', 'hype'],
  ['BENCHMARKS DON’T LIE', 'unless you cherry-pick', 'satire'],
  ['LATENCY IS A FEATURE', 'spinner goes brrr', 'joke'],
  ['P99 OF MY MOOD', 'spiky', 'joke'],
  ['OBSERVABILITY: WE SEE EVERYTHING', 'except the bug', 'satire'],
  ['ALERT FATIGUE ACHIEVED', 'pager: muted forever', 'joke'],
  ['ON-CALL AT 3AM', 'the real cloud bill', 'satire'],
  ['INCIDENT SEV-1', 'severity: pizza', 'joke'],
  ['POSTMORTEM: ACTION ITEMS', 'forgotten by next sprint', 'satire'],
  ['BLAMELESS CULTURE', 'except git blame', 'joke'],
  ['SRE: HOPE IS NOT A STRATEGY', 'but it is a vibe', 'joke'],
  ['SLO: 99.9% SARCASM', 'error budget: spent on memes', 'satire'],
  ['CHAOS MONKEY VISITED', 'resilience: emotional', 'joke'],
  ['IDEMPOTENT TEARS', 'safe to retry', 'joke'],
  ['EVENTUAL CONSISTENCY', 'of my life goals', 'joke'],
  ['CAP THEOREM AT LUNCH', 'pick two: burger fries nap', 'joke'],
  ['ACID TRANSACTIONS', 'not the scrapbook pack · calm down', 'joke'],
  ['BASE: BASICALLY AVAILABLE', 'soft state · eventual jokes', 'joke'],
  ['GRAPHQL: OVERFETCH MY ISSUES', 'underfetch my sleep', 'joke'],
  ['REST IN PEACE CRUD', 'POST /grief', 'joke'],
  ['WEBSOCKET STILL OPEN', 'like my emotional availability', 'joke'],
  ['SSE: SERVER SENT EXISTENTIALISM', 'stream of consciousness', 'joke'],
  ['GRPC: BUFFERS OF PAIN', 'protobuf my feelings', 'joke'],
  ['THUNDERING HERD OF PRs', 'reviewer down', 'joke'],
  ['BIKESHEDDING THE BUTTON COLOR', 'architecture can wait', 'satire'],
  ['YAK SHAVING CHAMPION', 'started with a typo', 'joke'],
  ['XY PROBLEM SOLVED', 'asked wrong · fixed worse', 'joke'],
  ['PREMATURE ABSTRACTION', 'factory of factories', 'satire'],
  ['DESIGN PATTERN BINGO', 'singleton of regret', 'joke'],
  ['MVC: MODEL VIEW CONFUSION', 'controller of chaos', 'joke'],
  ['MVVM: MORE VIBES VERY MEANING', 'bindings everywhere', 'joke'],
  ['CLEAN ARCHITECTURE', 'folders: 47 · features: 2', 'satire'],
  ['HEXAGONAL · BUT MAKE IT FASHION', 'ports and adapters and tears', 'joke'],
  ['DDD: DOMAIN DRIVEN DENIAL', 'ubiquitous language: “idk”', 'satire'],
  ['TDD: TEARS DRIVEN DEVELOPMENT', 'red green refactor cry', 'joke'],
  ['BDD: BEHAVIOR DRIVEN DRAMA', 'given when then argue', 'joke'],
  ['CI GREEN · PROD DOWN', 'classic plot twist', 'satire'],
  ['CD: CONTINUOUS DOOM', 'pipeline go brrr', 'joke'],
  ['ARTIFACT UPLOADED', 'confidence: still broken', 'joke'],
  ['CACHE HIT ON DOPAMINE', 'miss on sleep', 'joke'],
  ['CDN OF COPING MECHANISMS', 'edge: fine · origin: not', 'joke'],
  ['SSL CERT EXPIRED', 'like my warranty on sanity', 'joke'],
  ['DNS PROPAGATED MY PROBLEMS', 'globally', 'joke'],
  ['LOAD BALANCER OF EMOTIONS', 'round-robin breakdown', 'joke'],
  ['AUTOSCALING MY ANXIETY', 'min=1 max=∞', 'joke'],
  ['SPOT INSTANCE OF MOTIVATION', 'may be interrupted', 'joke'],
  ['COLD START OF MY BRAIN', 'lambda me to coffee', 'joke'],
  ['WARM POOL OF EXCUSES', 'ready for standup', 'joke'],
  ['SERVERLESS BUT NOT CARELESS', 'or so we claim', 'joke'],
  ['IAAS PAAS SAAS CHAOS', 'as a service', 'joke'],
  ['MULTI-CLOUD COPE', 'vendor lock-in: emotional', 'satire'],
  ['VENDOR LOCK-IN MY HEART', 'exit clause: none', 'joke'],
  ['OPEN SOURCE: FREE AS IN LUNCH', 'maintainer unpaid · forever', 'satire'],
  ['ISSUE #1: HELLO WORLD', 'still open', 'joke'],
  ['PR WELCOME', 'reviews: never', 'satire'],
  ['LICENSE: MIT MY PROBLEMS', 'as is · no warranty', 'joke'],
  ['SEMVER MAJOR BUMP', 'because feelings', 'joke'],
  ['BREAKING CHANGE: EVERYTHING', 'changelog: “improvements”', 'satire'],
  ['CHANGELOG.MD LIED', 'and that’s okay', 'joke'],
  ['README BADGE FARM', 'build: passing · truth: unclear', 'satire'],
  ['LIGHTHOUSE 100', 'on a blank page', 'joke'],
  ['BUNDLE SIZE: YES', 'users: on 3G · crying', 'satire'],
  ['TREE SHAKING MY HOPE', 'still shipped lodash', 'joke'],
  ['LAZY LOAD MY AMBITIONS', 'code-split the dreams', 'joke'],
  ['HYDRATION MISMATCH', 'react and I both confused', 'joke'],
  ['USEEFFECT INFINITE LOOP', 'dependency array: [pain]', 'joke'],
  ['KEY={INDEX} ENERGY', 'list reordered · chaos', 'joke'],
  ['PROP DRILLING TO THE CORE', 'context would be nice', 'joke'],
  ['REDUX FOR A TOGGLE', 'enterprise ready', 'satire'],
  ['STATE MANAGEMENT HELL', 'zustand saved me · maybe', 'joke'],
  ['SSR SSR SSR', 'server says hello · client says who?', 'joke'],
  ['ISR: INCREMENTAL STRESS REGENERATION', 'revalidate: always', 'joke'],
  ['EDGE RUNTIME EDGE CASE', 'works until it doesn’t', 'joke'],
  ['TAILWIND: CLASS SOUP', 'beautiful soup', 'joke'],
  ['!IMPORTANT WINS AGAIN', 'specificity wars', 'joke'],
  ['Z-INDEX: 9999', 'still under the modal', 'joke'],
  ['DARK MODE FIXED', 'light mode: abandoned', 'joke'],
  ['A11Y: AFTER LAUNCH', 'famous last words', 'satire'],
  ['ARIA LABEL: “BUTTON”', 'peak accessibility', 'satire'],
  ['KEYBOARD TRAP', 'tab tab tab help', 'joke'],
  ['FOCUS OUTLINE REMOVED', 'designer smiled · users lost', 'satire'],
  ['PIXEL PERFECT · LOGIC BROKEN', 'figma doesn’t run tests', 'joke'],
  ['DESIGN SYSTEM: 12 BUTTONS', 'all slightly different', 'satire'],
  ['SPACING: 8PX GRID', 'except when 7', 'joke'],
  ['FIGMA HANDOFF', 'dev: which frame is real?', 'joke'],
  ['LOREM IPSUM SHIPPED', 'content team: …', 'joke'],
  ['COPY TBD', 'for 14 sprints', 'joke'],
  ['LEGAL REVIEW PENDING', 'since forever', 'joke'],
  ['SECURITY: WE’LL ADD AUTH LATER', 'later = never', 'satire'],
  ['OWASP TOP 10 BINGO', 'SQL injection free space', 'joke'],
  ['XSS IN MY COMMIT MSG', 'alert(“hi”) ', 'joke'],
  ['CSRF TOKEN OF APPRECIATION', 'validate before trust', 'joke'],
  ['ROTATE YOUR SECRETS', 'and your sleep schedule', 'joke'],
  ['.ENV COMMITTED', 'classic speedrun', 'satire'],
  ['API KEY IN THE FRONTEND', 'bold strategy', 'satire'],
  ['RATE LIMIT EXCEEDED', 'touch grass', 'joke'],
  ['QUOTA: 0', 'cloud said no', 'joke'],
  ['BILLING ALERT', 'the real pagerduty', 'joke'],
  ['COST OPTIMIZATION SPRINT', 'delete everything', 'satire'],
  ['FREE TIER ENDED', 'so did my smile', 'joke'],
  ['ENTERPRISE PLAN ENERGY', 'features: grayed out', 'satire'],
  ['SSO: SORRY SIGN-ON', 'redirect loop of doom', 'joke'],
  ['OAUTH DANCE COMPLETE', 'token: expired already', 'joke'],
  ['JWT IN LOCALSTORAGE', 'security team: screaming', 'satire'],
  ['SESSION COOKIE OF DOUBT', 'HttpOnly · hopefully', 'joke'],
  ['2FA: TOO MANY FACTORS', 'of annoyance', 'joke'],
  ['PASSWORD: PASSWORD123', 'audit finding #1', 'satire'],
  ['PASSWORD MANAGER SAID NO', 'reuse is a lifestyle', 'joke'],
  ['CAPTCHA PROVES I’M HUMAN', 'barely', 'joke'],
  ['BOTS WRITE BETTER TESTS', 'uncomfortable truth', 'satire'],
  ['SCRUM MASTER LEFT THE CHAT', 'velocity: vibes', 'joke'],
  ['VELOCITY UP · QUALITY DOWN', 'charts don’t cry', 'satire'],
  ['BURNDOWN CHART ON FIRE', 'literally the metaphor', 'joke'],
  ['SPRINT GOAL: SURVIVE', 'accepted', 'wholesome'],
  ['RETRO: WHAT WENT WELL', 'the snacks', 'joke'],
  ['ACTION ITEM: BE BETTER', 'measurable · somehow', 'satire'],
  ['OKRS: OBJECTIVELY KILLING REALISM', 'key result: ship jokes', 'joke'],
  ['NORTH STAR METRIC: MEMES', 'alignment achieved', 'hype'],
  ['STAKEHOLDER ALIGNMENT', 'herding cats · in Jira', 'satire'],
  ['SCOPE CREEP ENTERED THE DUNGEON', 'party wiped', 'joke'],
  ['MVP: MINIMUM VIABLE PANIC', 'shipped', 'hype'],
  ['V1 IS A LIFESTYLE', 'v2 is a myth', 'joke'],
  ['REWRITE IN RUST', 'rewrite in regret', 'satire'],
  ['ELECTRON APP: ONLY 400MB', 'hello world', 'joke'],
  ['NATIVE WHEN?', 'soon™', 'joke'],
  ['CROSS-PLATFORM: CROSS TO BEAR', 'bugs on every OS', 'joke'],
  ['WINDOWS PATH\\\\ESCAPES', 'unix users: laughing', 'joke'],
  ['CRLF VS LF WAR', 'editorconfig: peacemaker', 'joke'],
  ['TABS VS SPACES', 'civilization ended here', 'joke'],
  ['PRETTIER SAVED THE MARRIAGE', 'format on save · forever', 'wholesome'],
  ['ESLINT --FIX MY LIFE', 'auto-fix the trauma', 'joke'],
  ['HUSKY PRE-COMMIT', 'dog went brrr', 'joke'],
  ['CI FAILED ON A TYPO', 'character development', 'joke'],
  ['GREEN BUILD = SHIP', 'philosophy of champions', 'hype'],
  ['ALL TESTS GREEN', 'imposter syndrome: buffering', 'joke'],
  ['YOU FIXED IT', 'the universe noticed', 'wholesome'],
  ['SHIPPED AND PROUD', 'changelog: chaos curated', 'hype'],
  ['ORBITAL APPROVES THIS PR', 'mothership has spoken', 'hype'],
  ['2050 CALLED · WANTS THIS DIFF', 'legacy IDEs could never', 'hype'],
  ['DOPAMINE DEPLOYED', 'next hit: in 45s (throttle)', 'joke'],
  ['CELEBRATION THROTTLED', 'even joy has rate limits', 'satire'],
  ['RANDOM JOKE LOADED', 'entropy: chef’s kiss', 'joke'],
  ['ANOTHER ONE', 'dj khaled of green checks', 'hype'],
  ['NO REPEATS ON OUR WATCH', 'recent-seen buffer online', 'joke'],
];

const PACK_SPECIALS = [
  {
    id: 'acid-pinterest-board',
    kinds: ['*'],
    packs: ['acid'],
    tone: 'satire',
    anim: 'stamp-spin',
    line: 'PINNED TO THE CHAOS BOARD',
    subline: 'Pinterest could never ship this PR',
  },
  {
    id: 'mothership-hr',
    kinds: ['*'],
    packs: ['mothership'],
    tone: 'joke',
    anim: 'pulse-zoom',
    line: 'HR ON THE MOTHERSHIP SAYS GG',
    subline: 'abduction optional · shipping mandatory',
  },
  {
    id: 'glitch-fax',
    kinds: ['*'],
    packs: ['glitch'],
    tone: 'satire',
    anim: 'glitch-text',
    line: 'FAXED TO PRODUCTION',
    subline: 'tape hiss: aesthetic only',
  },
  {
    id: 'soft-cow-union',
    kinds: ['*'],
    packs: ['soft'],
    tone: 'wholesome',
    anim: 'float-soft',
    line: 'THE COW UNION APPROVES',
    subline: 'gentle win · no overtime for moos',
  },
  {
    id: 'root-sudo-nap',
    kinds: ['*'],
    packs: ['root'],
    tone: 'joke',
    anim: 'typewriter',
    line: 'sudo nap · ACCESS DENIED',
    subline: 'stay up and enjoy the green',
  },
];

function slug(line, i) {
  return (
    'dj-' +
    i +
    '-' +
    line
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 40)
  );
}

const bites = SOURCES.map(([line, subline, tone], i) => ({
  id: slug(line, i),
  kinds: ['*'],
  packs: ['*'],
  tone,
  anim: ANIMS[i % ANIMS.length],
  line,
  subline,
}));

const existingPath = OUT;
let previous = [];
try {
  previous = JSON.parse(fs.readFileSync(existingPath, 'utf8')).bites || [];
} catch {
  /* first run */
}

const byId = new Map();
for (const b of [...previous, ...bites, ...PACK_SPECIALS]) {
  byId.set(b.id, b);
}

// Normalize: ensure * kinds for maximum random coverage on preview
const merged = [...byId.values()].map((b) => {
  if (!b.kinds.includes('*') && b.kinds.length <= 2) {
    return { ...b, kinds: ['*', ...b.kinds] };
  }
  return b;
});

const doc = {
  version: 2,
  note: 'Agent-extensible. Inspired by programmer humor (e.g. github.com/shrutikapoor08/devjoke). Run node scripts/expand-bites.mjs to regenerate core set; append custom bites anytime.',
  sourceIdeas: 'https://github.com/shrutikapoor08/devjoke',
  anims: ANIMS,
  bites: merged,
};

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, JSON.stringify(doc, null, 2) + '\n');
console.log(`✓ ${merged.length} bites → ${OUT}`);
